import sys
import os

# Compatibility for lyricsgenius/pydantic on Python < 3.11
if sys.version_info < (3, 11):
    import typing
    try:
        from typing_extensions import Self
        typing.Self = Self
    except ImportError:
        pass

# Removed firebase-functions imports for standard API hosting
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import joblib
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
import requests
from dotenv import load_dotenv
import re
import hashlib
import lyricsgenius

# Ensure UTF-8 output on Windows to avoid UnicodeEncodeError with emojis/special chars
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

load_dotenv()

path = os.path.dirname(os.path.abspath(__file__))

print("Loading joblib models generated by the Notebook...", flush=True)
data = joblib.load(os.path.join(path, "recommender_data.joblib"))
pipeline = data["pipeline"]
df = data["df"]
df_final = data["df_final"]

# --- GLOBAL UTILS ---
def normalize_title(t):
    return re.sub(r'\(.*?\)', '', str(t)).lower().strip()

def normalize_artist(a):
    # Use only the lead artist for duplicate detection
    return str(a).split(';')[0].strip().lower()

app = FastAPI(title="Song Recommender API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # For Render development, we start broad and can restrict later
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class RecommendRequest(BaseModel):
    song_name: str
    artist: str = None  # Optional artist filter for disambiguation
    n: int = 5
    exclude: list[str] = []

class LyricsRequest(BaseModel):
    track_name: str
    artist: str

class ExternalRecommendRequest(BaseModel):
    song_name: str
    artists: str
    danceability: float
    energy: float
    key: int
    loudness: float
    mode: int
    speechiness: float
    acousticness: float
    instrumentalness: float
    liveness: float
    valence: float
    tempo: float
    track_genre: str = ""
    n: int = 5

# --- 100% NATIVE NOTEBOOK LOGIC FOR INTERNAL SONGS ---

def find_song(query, artist=None):
    """Helper to find a song by name, returning its row with prioritized matching."""
    q = query.strip()
    
    # 1. Exact Match (Case-Insensitive)
    exact_matches = df[df['track_name'].str.fullmatch(re.escape(q), case=False, na=False)]
    if artist:
        # Filter by artist if provided
        artist_matches = exact_matches[exact_matches['artists'].str.contains(re.escape(artist), case=False, na=False)]
        if not artist_matches.empty: return artist_matches.sort_values('popularity', ascending=False).iloc[0]
    elif not exact_matches.empty:
        return exact_matches.sort_values('popularity', ascending=False).iloc[0]

    # 2. Starts-With Match (Case-Insensitive)
    starts_matches = df[df['track_name'].str.startswith(q, na=False)]
    if not starts_matches.empty:
        return starts_matches.sort_values('popularity', ascending=False).iloc[0]

    # 3. Substring Match (Case-Insensitive)
    substring_matches = df[df['track_name'].str.contains(re.escape(q), case=False, na=False)]
    if not substring_matches.empty:
        return substring_matches.sort_values('popularity', ascending=False).iloc[0]
    
    # If no match, raise error
    raise ValueError(f"Song '{query}' not found in dataset.")

def notebook_recommend(song_name, n=5, w_audio=0.3, w_genre=0.7, exclude=None):
    """Recommends similar songs with duplicate filtering and returns a style-ready DataFrame."""
    # 1. Find the target song
    target_song = find_song(song_name)
    target_idx = target_song.name
    
    # 2. Extract vectors
    audio_cols = [col for col in df_final.columns if col.startswith('num__')]
    genre_cols = [col for col in df_final.columns if col.startswith('cat__')]
    
    target_audio = df_final.loc[[target_idx], audio_cols]
    target_genre = df_final.loc[[target_idx], genre_cols]
    
    # 3. Calculate similarities on-the-fly
    audio_sims = cosine_similarity(target_audio, df_final[audio_cols])[0]
    genre_sims = cosine_similarity(target_genre, df_final[genre_cols])[0]
    
    # 4. Weighted combination
    total_sims = (w_audio * audio_sims) + (w_genre * genre_sims)
    
    # 5. Filter & Deduplicate
    results = df.copy()
    results['similarity_score'] = total_sims
    results = results.drop(target_idx)
    candidates = results.sort_values('similarity_score', ascending=False).head(n * 2)
    
    final_list = []
    seen = set()
    # Add the target song to seen so it doesn't appear in recommendations
    seen.add((normalize_title(target_song['track_name']), normalize_artist(target_song['artists'])))
    # Also exclude previously played songs from appearing in recommendations
    if exclude:
        for ex_name in exclude:
            seen.add((normalize_title(ex_name), ''))
    
    for _, row in candidates.iterrows():
        norm_t = normalize_title(row['track_name'])
        norm_a = normalize_artist(row['artists'])
        # Check both exact (title, artist) match and title-only match for excluded songs
        if (norm_t, norm_a) not in seen and (norm_t, '') not in seen:
            final_list.append(row)
            seen.add((norm_t, norm_a))
            if len(final_list) == n: break
                
    top_n = pd.DataFrame(final_list)
    
    # 6. Add Meta-data
    reasons = []
    for _, row in top_n.iterrows():
        if row['track_genre'] == target_song['track_genre']:
            reasons.append('Matches genre and audio profile')
        elif abs(row['energy'] - target_song['energy']) < 0.1:
            reasons.append('Very similar energy and vibe')
        else:
            reasons.append('Similar sonic qualities')
            
    top_n['Reason'] = reasons
    top_n['Similarity %'] = (top_n['similarity_score'] * 100).round(1)
    
    return top_n, target_song


# --- NATIVE NOTEBOOK LOGIC ADAPTED FOR SPOTIFY EXTERNAL SONGS ---

def external_recommend(spotify_req: ExternalRecommendRequest, w_audio=0.3, w_genre=0.7, exclude=None):
    feature_dict = {
        'danceability': spotify_req.danceability,
        'energy': spotify_req.energy,
        'key': spotify_req.key,
        'loudness': spotify_req.loudness,
        'mode': spotify_req.mode,
        'speechiness': spotify_req.speechiness,
        'acousticness': spotify_req.acousticness,
        'instrumentalness': spotify_req.instrumentalness,
        'liveness': spotify_req.liveness,
        'valence': spotify_req.valence,
        'tempo': spotify_req.tempo,
        'track_genre': spotify_req.track_genre
    }
    
    # Construct exact same formatted row as df_final by passing through pipeline
    df_raw_input = pd.DataFrame([feature_dict])
    target_vector_raw = pipeline.transform(df_raw_input)
    column_names = pipeline.named_steps['preprocessor'].get_feature_names_out()
    target_df_final = pd.DataFrame(target_vector_raw, columns=column_names)
    
    audio_cols = [col for col in df_final.columns if col.startswith('num__')]
    genre_cols = [col for col in df_final.columns if col.startswith('cat__')]
    
    target_audio = target_df_final[audio_cols]
    target_genre = target_df_final[genre_cols]
    
    # 3. Calculate similarities on-the-fly against all internal database songs
    audio_sims = cosine_similarity(target_audio, df_final[audio_cols])[0]
    genre_sims = cosine_similarity(target_genre, df_final[genre_cols])[0]
    
    # 4. Weighted combination
    total_sims = (w_audio * audio_sims) + (w_genre * genre_sims)
    
    # 5. Filter & Deduplicate
    results = df.copy()
    results['similarity_score'] = total_sims
    candidates = results.sort_values('similarity_score', ascending=False).head(spotify_req.n * 2)
    
    def normalize_title(t):
        return re.sub(r'\(.*?\)', '', t).lower().strip()
    def normalize_artist(a):
        return a.split(';')[0].strip().lower()
    
    final_list = []
    seen = set()
    seen.add((normalize_title(spotify_req.song_name), normalize_artist(spotify_req.artists)))
    # Also exclude previously played songs
    if exclude:
        for ex_name in exclude:
            seen.add((normalize_title(ex_name), ''))
    
    for _, row in candidates.iterrows():
        norm_title = normalize_title(row['track_name'])
        norm_artist = normalize_artist(row['artists'])
        if (norm_title, norm_artist) not in seen and (norm_title, '') not in seen:
            final_list.append(row)
            seen.add((norm_title, norm_artist))
            if len(final_list) == spotify_req.n: break
                
    top_n = pd.DataFrame(final_list)
    
    reasons = []
    for _, row in top_n.iterrows():
        if row['track_genre'] == spotify_req.track_genre:
            reasons.append('Matches genre and audio profile')
        elif abs(row['energy'] - spotify_req.energy) < 0.1:
            reasons.append('Very similar energy and vibe')
        else:
            reasons.append('Similar sonic qualities')
            
    top_n['Reason'] = reasons
    top_n['Similarity %'] = (top_n['similarity_score'] * 100).round(1)
    
    return top_n


def fetch_youtube_as_recommendation(song_name: str, n: int, exclude: list[str] = None):
    yt_api_key = os.environ.get("YOUTUBE_API_KEY")
    if not yt_api_key or yt_api_key == "YOUR_YOUTUBE_DATA_API_KEY":
        return {"error": "YouTube fallback disabled (Missing API Key)"}

    # 1. Search YouTube for metadata
    try:
        response = requests.get(
            "https://www.googleapis.com/youtube/v3/search",
            params={
                "q": f"{song_name} audio",
                "part": "snippet",
                "maxResults": 1,
                "type": "video",
                "key": yt_api_key
            }
        )
        if response.status_code != 200:
            return {"error": "YouTube search failed"}
        
        yt_res = response.json()
        if not yt_res.get("items"):
            return {"error": f"Could not find '{song_name}' on YouTube"}

        yt_item = yt_res["items"][0]
        track_name = yt_item["snippet"]["title"]
        artist_name = yt_item["snippet"]["channelTitle"].replace(" - Topic", "")
        image_url = yt_item["snippet"]["thumbnails"]["high"]["url"] if "high" in yt_item["snippet"]["thumbnails"] else yt_item["snippet"]["thumbnails"]["default"]["url"]
        
        # 2. Surrogate Recommendations
        # Strategy: Find songs in OUR dataset by the same artist
        artist_matches = df[df['artists'].str.contains(artist_name.split()[0], case=False, na=False)]
        
        if not artist_matches.empty:
            # Pick their most popular song as a surrogate seed
            surrogate = artist_matches.sort_values('popularity', ascending=False).iloc[0]
            top_n, _ = notebook_recommend(surrogate['track_name'], n, exclude=exclude)
        else:
            # If no artist match, return globally popular songs
            top_n = df.sort_values('popularity', ascending=False).head(n)
            # Add dummy columns for compatibility
            top_n = top_n.copy()
            top_n['similarity_score'] = 0.0
            top_n['Similarity %'] = "0"
            top_n['Reason'] = "Trending Track"

        results = []
        for _, row in top_n.iterrows():
            sim_val = row.get('similarity_score', 0)
            sim_pct = row.get('Similarity %', round(sim_val * 100, 1))
            results.append({
                "track_name": row['track_name'],
                "artists": row['artists'],
                "album_name": row['album_name'],
                "track_genre": row['track_genre'],
                "similarity": float(sim_val),
                "similarity_percent": str(sim_pct),
                "reason": row.get('Reason', "Trending Track")
            })

        return {
            "query": song_name,
            "matched_song": track_name,
            "matched_artists": artist_name,
            "image_url": image_url,
            "recommendations": results,
            "fallback": True
        }
    except Exception as e:
        return {"error": str(e)}


def enrich_recommendations_with_cache(recommendations):
    """Checks each recommendation against local & Firestore cache to provide instant thumbnails/IDs."""
    enriched = []
    for rec in recommendations:
        norm_t = normalize_string_for_cache(rec['track_name'])
        norm_a = normalize_string_for_cache(rec['artists'])
        check_query = f"{norm_t} {norm_a} official audio"
        check_id = hashlib.md5(check_query.encode('utf-8')).hexdigest()
        
        cached_id = None
        if check_id in PLAY_CACHE:
            cached_id = PLAY_CACHE[check_id]
        elif FIRESTORE_AVAILABLE:
            try:
                snap = db.collection('youtube_cache').document(check_id).get()
                if snap.exists:
                    cached_id = snap.to_dict().get('videoId')
                    PLAY_CACHE[check_id] = cached_id
            except: pass
        
        rec['videoId'] = cached_id
        enriched.append(rec)
    return enriched

@app.post("/recommend")
def recommend_songs(req: RecommendRequest):
    song_name = req.song_name
    n = req.n
    
    try:
        # Use artist hint if available to ensure accurate selection from autocomplete
        target_song = find_song(song_name, artist=req.artist)
    except ValueError:
        print(f"'{song_name}' not in local memory. Falling back to YouTube search...", flush=True)
        yt_data = fetch_youtube_as_recommendation(song_name, n, exclude=req.exclude)
        if 'recommendations' in yt_data:
            yt_data['recommendations'] = enrich_recommendations_with_cache(yt_data['recommendations'])
        return yt_data
        
    # If it exists, use native notebook execution!
    top_n, t_song = notebook_recommend(song_name, n, exclude=req.exclude)
    
    results = []
    for _, row in top_n.iterrows():
        results.append({
            "track_name": row['track_name'],
            "artists": row['artists'],
            "album_name": row['album_name'],
            "track_genre": row['track_genre'],
            "similarity": row['similarity_score'],
            "similarity_percent": row['Similarity %'],
            "reason": row['Reason']
        })
    
    # Enrich with cache before returning
    results = enrich_recommendations_with_cache(results)
        
    return {
        "query": song_name,
        "matched_song": t_song['track_name'],
        "matched_artists": t_song['artists'],
        "image_url": None, 
        "recommendations": results,
        "source": "local",
        "fallback": False
    }

@app.get("/search")
def search_suggestions(q: str = "", limit: int = 8):
    """Fast autocomplete from the local dataset — no external API."""
    if not q or len(q.strip()) < 2:
        return {"suggestions": []}
    
    query = q.strip()
    results = []
    seen = set()

    # 1. Local Dataset Matches (Substring)
    matches = df[df['track_name'].str.contains(query, case=False, na=False, regex=False)]
    if not matches.empty:
        matches = matches.sort_values('popularity', ascending=False)
        for _, row in matches.iterrows():
            key = (normalize_title(row['track_name']), normalize_artist(row['artists']))
            if key not in seen:
                seen.add(key)
                results.append({
                    "track_name": row['track_name'],
                    "artists": row['artists'],
                    "album_name": row['album_name'],
                    "track_genre": row['track_genre'],
                    "popularity": int(row['popularity']),
                })
            if len(results) >= limit: break

    # 2. Firestore Cache Matches (Prefix - for discovered tracks)
    if FIRESTORE_AVAILABLE and len(results) < limit:
        try:
            cache_query = db.collection('youtube_cache')\
                .where('raw_track', '>=', query)\
                .where('raw_track', '<=', query + '\uf8ff')\
                .limit(limit)\
                .get()
            
            for doc in cache_query:
                doc_data = doc.to_dict()
                nt = normalize_title(doc_data.get('raw_track', ''))
                na = normalize_artist(doc_data.get('raw_artist', ''))
                key = (nt, na)
                if key not in seen:
                    seen.add(key)
                    results.append({
                        "track_name": doc_data.get('raw_track'),
                        "artists": doc_data.get('raw_artist'),
                        "album_name": "Cached Discovery",
                        "track_genre": "External",
                        "popularity": 0 
                    })
                if len(results) >= limit: break
        except Exception as e:
            print(f"Firestore suggestion error: {e}")
    
    return {"suggestions": results[:limit]}


@app.post("/lyrics")
def fetch_lyrics(req: LyricsRequest):
    """Fetches full lyrics from Genius on-demand."""
    token = os.environ.get("GENIUS_ACCESS_TOKEN")
    if not token or token == "PASTE_YOUR_TOKEN_HERE":
        return {"error": "Genius API Access Token missing. Add it to .env in the functions/ folder."}

    try:
        # Initialize Genius with the token
        # We disable verbose and exclude non-songs to keep it fast
        genius = lyricsgenius.Genius(token)
        genius.verbose = False
        genius.remove_section_headers = False # Keep them for now as they help structure

        # Search for the song
        # We use a combined query for accuracy
        song = genius.search_song(req.track_name, req.artist)
        
        if not song:
            return {"error": f"Lyrics not found for '{req.track_name}' by {req.artist}"}

        # Clean up the lyrics text slightly
        # Genius often adds a "Lyrics" prefix and "Embed" suffix
        raw_lyrics = song.lyrics
        
        # Simple cleanup of Genius specific artifacts
        cleaned = re.sub(r'^[0-9]+ Lyrics', '', raw_lyrics) # Remove leading "X Lyrics"
        cleaned = re.sub(r'Embed$', '', cleaned)            # Remove trailing "Embed"
        cleaned = re.sub(r'[0-9]*Embed$', '', cleaned)       # Sometimes it's number-Embed
        
        return {
            "track_name": song.title,
            "artist": song.artist,
            "lyrics": cleaned,
            "source": "genius",
            "url": song.url
        }
    except Exception as e:
        print(f"Lyrics Error: {e}")
        return {"error": f"Failed to fetch lyrics: {str(e)}"}


from firebase_admin import credentials, initialize_app, firestore

try:
    # Check if we have a service account key path in env
    cred_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if cred_path and os.path.exists(cred_path):
        cred = credentials.Certificate(cred_path)
        initialize_app(cred)
    else:
        # Fallback to default credentials (works natively in Firebase cloud)
        initialize_app()
    
    db = firestore.client()
    FIRESTORE_AVAILABLE = True
    print("✓ Firestore connected successfully.")
except Exception as e:
    print(f"Firestore not available: {e}. Falling back to memory cache.")
    FIRESTORE_AVAILABLE = False
    db = None

PLAY_CACHE = {}

class PlayRequest(BaseModel):
    track_name: str
    artists: str

def normalize_string_for_cache(s):
    # Lowercase, strip spaces, remove (Remix), - Live, etc for max collisions
    s = str(s).lower()
    s = re.sub(r'\(.*?\)', '', s)
    s = re.sub(r'- live.*?', '', s)
    s = re.sub(r'- radio edit.*?', '', s)
    s = re.sub(r'- remix.*?', '', s)
    return s.strip()

@app.post("/play")
def fetch_youtube_playback(req: PlayRequest):
    norm_track = normalize_string_for_cache(req.track_name)
    norm_artist = normalize_string_for_cache(req.artists)
    
    query = f"{norm_track} {norm_artist} official audio"
    doc_id = hashlib.md5(query.encode('utf-8')).hexdigest()
    
    # 1. Try Memory Cache
    if doc_id in PLAY_CACHE:
        return {"videoId": PLAY_CACHE[doc_id], "source": "memory"}
        
    # 2. Try Firestore Cache
    if FIRESTORE_AVAILABLE:
        try:
            doc_ref = db.collection('youtube_cache').document(doc_id)
            doc_snap = doc_ref.get()
            if doc_snap.exists:
                vid = doc_snap.to_dict().get('videoId')
                PLAY_CACHE[doc_id] = vid # Warm up local cache
                return {"videoId": vid, "source": "firestore"}
        except Exception as e:
            print(f"Firestore read error: {e}")
            
    yt_api_key = os.environ.get("YOUTUBE_API_KEY")
    if not yt_api_key or yt_api_key == "YOUR_YOUTUBE_DATA_API_KEY":
        return {"error": "Native playback is disabled (Missing YOUTUBE_API_KEY in .env)"}
        
    # 3. YouTube API Fallback
    try:
        response = requests.get(
            "https://www.googleapis.com/youtube/v3/search",
            params={
                "q": query,
                "part": "snippet",
                "maxResults": 1,
                "type": "video",
                "videoEmbeddable": "true", # CRITICAL: Only find videos we can actually play
                "videoSyndicated": "true",
                "key": yt_api_key
            }
        )
        
        if response.status_code == 403:
            return {"error": "YouTube API Quota Exceeded. Please try again tomorrow or use a different key."}
            
        if response.status_code == 200:
            data = response.json()
            if data.get("items"):
                vid = data["items"][0]["id"]["videoId"]
                
                # Proactively set cache
                PLAY_CACHE[doc_id] = vid
                if FIRESTORE_AVAILABLE:
                    try:
                        db.collection('youtube_cache').document(doc_id).set({
                            'videoId': vid, 
                            'query': query, 
                            'raw_track': req.track_name, 
                            'raw_artist': req.artists,
                            'timestamp': firestore.SERVER_TIMESTAMP
                        })
                    except Exception as e:
                        print(f"Firestore write error: {e}")
                        
                return {"videoId": vid, "source": "youtube_api"}
        
        # If the restrictive query failed, try a broader search once
        if "official audio" in query:
            broad_query = f"{req.track_name} {req.artists}"
            response = requests.get(
                "https://www.googleapis.com/youtube/v3/search",
                params={
                    "q": broad_query,
                    "part": "snippet",
                    "maxResults": 1,
                    "type": "video",
                    "videoEmbeddable": "true",
                    "key": yt_api_key
                }
            )
            if response.status_code == 200:
                data = response.json()
                if data.get("items"):
                    vid = data["items"][0]["id"]["videoId"]
                    return {"videoId": vid, "source": "youtube_api_broad"}

        return {"error": f"Video not found or is restricted. (Status: {response.status_code})"}
    except Exception as e:
        return {"error": f"Playback error: {str(e)}"}

# Cloud function wrapper removed for standard ASGI hosting
# To run locally or on Render: uvicorn main:app --host 0.0.0.0 --port 8000
